/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CirclesRouteImport } from './routes/circles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CirclesIdRouteImport } from './routes/circles.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesRoute = CirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesIdRoute = CirclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CirclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circles': typeof CirclesRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/circles/$id': typeof CirclesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circles': typeof CirclesRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/circles/$id': typeof CirclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circles': typeof CirclesRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/circles/$id': typeof CirclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circles'
    | '/discover'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/circles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circles'
    | '/discover'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/circles/$id'
  id:
    | '__root__'
    | '/'
    | '/circles'
    | '/discover'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/circles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CirclesRoute: typeof CirclesRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles': {
      id: '/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof CirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/$id': {
      id: '/circles/$id'
      path: '/$id'
      fullPath: '/circles/$id'
      preLoaderRoute: typeof CirclesIdRouteImport
      parentRoute: typeof CirclesRoute
    }
  }
}

interface CirclesRouteChildren {
  CirclesIdRoute: typeof CirclesIdRoute
}

const CirclesRouteChildren: CirclesRouteChildren = {
  CirclesIdRoute: CirclesIdRoute,
}

const CirclesRouteWithChildren =
  CirclesRoute._addFileChildren(CirclesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CirclesRoute: CirclesRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
